
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Includo in file di configurazione della comuncazione ModBus
modbus: !include modbus.yaml

homeassistant:
  customize:
    sensor.abb_angle_power_total:
      icon: mdi:angle-acute
    sensor.abb_angle_power_l1:
      icon: mdi:angle-acute
    sensor.abb_angle_power_l2:
      icon: mdi:angle-acute
    sensor.abb_angle_power_l3:
      icon: mdi:angle-acute
    sensor.abb_angle_voltage_l1:
      icon: mdi:angle-acute
    sensor.abb_angle_voltage_l2:
      icon: mdi:angle-acute
    sensor.abb_angle_voltage_l3:
      icon: mdi:angle-acute
    sensor.abb_angle_current_l1:
      icon: mdi:angle-acute
    sensor.abb_angle_current_l2:
      icon: mdi:angle-acute
    sensor.abb_angle_current_l3:
      icon: mdi:angle-acute
    sensor.abb_cosphi_total:
      icon: mdi:angle-acute
    sensor.abb_cosphi_l1:
      icon: mdi:angle-acute
    sensor.abb_cosphi_l2:
      icon: mdi:angle-acute
    sensor.abb_cosphi_l3:
      icon: mdi:angle-acute
